apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init-db.sh: |
    #!/bin/bash
    set -e
    
    if [ -n "$POSTGRES_MULTIPLE_DATABASES" ]; then
      for db in $(echo $POSTGRES_MULTIPLE_DATABASES | tr ',' ' '); do
        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE DATABASE "$db";
EOSQL
      done
    fi