apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init-db.sh: |
    #!/bin/bash
    set -e

    if [ -n "$POSTGRES_MULTIPLE_DATABASES" ]; then
      for db in $(echo "$POSTGRES_MULTIPLE_DATABASES" | tr ',' ' '); do
        echo "Creating database: $db"
        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        SELECT 'CREATE DATABASE "$db"'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$db')\gexec
    EOSQL
      done
    fi