services:
  react-app:
    image: react-app:latest
    container_name: react-app
    build:
      context: ./react-app
      dockerfile: ./Dockerfile
      target: build
    ports:
      - "${REACT_PORT}:${REACT_PORT}"
    volumes:
      - ./react-app/app:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - TZ=${TZ}
    env_file:
      - .env
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_MULTIPLE_DATABASES: ${DB_MULTIPLE_DATABASES}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      TZ: ${TZ}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./init_scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  go-server:
    image: go-server:latest
    container_name: go-server
    build:
      context: ./go-server
      dockerfile: ./Dockerfile
      target: build
    ports:
      - "${GO_PORT}:${GO_PORT}"
    volumes:
      - ./go-server/app:/app
    environment:
      - GO_ENV=development
    env_file:
      - .env

  python-service:
    image: python-service:latest
    container_name: python-service
    build:
      context: ./python-service
      dockerfile: ./Dockerfile
      target: build
    ports:
      - "${PYTHON_PORT}:${PYTHON_PORT}"
    volumes:
      - ./python-service/app:/app
    environment:
      - PYTHON_ENV=development
    env_file:
      - .env

  keycloak-data:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-data
    command: start-dev
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres-db
      - KC_DB_URL_PORT=${DB_PORT}
      - KC_DB_URL_DATABASE=${KEYCLOAK_DB_NAME}
      - KC_DB_USERNAME=${DB_USER}
      - KC_DB_PASSWORD=${DB_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_HTTP_PORT=${KEYCLOAK_PORT}
    ports:
      - "${KEYCLOAK_PORT}:${KEYCLOAK_PORT}"
    volumes:
      - ./keycloak-data:/opt/keycloak/data
    depends_on:
      postgres-db:
        condition: service_healthy
    env_file:
      - .env